name: Run Hot Stock Bot

on:
  schedule:
    - cron: '15 14 * * 0-4' # 台灣 22:15 執行
    - cron: '0 0 * * 1-5'   # 台灣 08:00 執行
  workflow_dispatch:

jobs:
  run_hot_bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install yfinance pandas requests lxml
      - name: Run Scan
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python hot_stock_bot.py
